### ISSUE TITLE
problem load img users

### ISSUE THREAD

**Issue by rezolixx** [ItsOnlyBinary/kiwiirc-plugin-avatar-upload#9]
**Erreur lors du téléchargement de l'avatar** 

Everything is in place I don't know why it doesn't load the image please help me

file config.json 
### "plugin-avatar-upload" : {
    "api_url": "https://app.tchat.chat/api.php",
    "avatars_url": "https://app.tchat.chat/"
    },    

file api.php

### const JWT_ALGORITHM = 'HS256';
const THUMBNAIL_LARGE = 200;
const THUMBNAIL_SMALL = 80;

const JWT_KEY = '3bAayOglA/i4FAdk/gQ4PKOeOXkjtFkzYwWdf9EBBtU=';
const AVATAR_DIR = '/var/www/html/kiwiirc/static/plugins/avatar/';
const ALLOWED_DOMAINS = [
    'https://app.tchat.chat',
    'https://*.tchat.chat',
];

**ircd Version unrealircd**

debug

2024/10/16 02:45:46.198440 L_DEBUG client:2 in c.ThrottledRecv.Output
2024/10/16 02:45:46.198470 L_DEBUG client:2 Traffic (Client->) EXTJWT *
2024/10/16 02:45:46.198475 L_DEBUG client:2 signal:data :irc.tchat.chat EXTJWT * * * eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijoic2FXIiwiY2hhbm5lbCI6IiIsImNtb2RlcyI6W10sImV4cCI6MTcyOTAzOTYwNiwiaXNzIjoiaXJjLnRjaGF0LmNoYXQiLCJqb2luZWQiOjAsInN1YiI6InNhdyIsInVtb2RlcyI6W119.O74ARR
2024/10/16 02:45:46.198481 L_DEBUG client:2 signal:data :irc.tchat.chat EXTJWT * * gZ71bVPl6k78YxGh4LIwAN0Y7fzAt-LhvkKgk

**Comment by rezolixx** [comment]
Could you please help me? @ItsOnlyBinary

**Comment by ItsOnlyBinary** [comment]
I would suggest checking your httpd's error logs for issues with php like incorrect directory permissions etc

**Comment by rezolixx** [comment]
Thanks for replay @ItsOnlyBinary  It downloads pictures of other people on the network but I can't find anything in the folder.

102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/small/technicien.png HTTP/1.1" 404 3066 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/small/rocking.png HTTP/1.1" 404 3066 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/large/technicien.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/large/rocking.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/small/g_w.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/small/poko.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/large/g_w.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:32 +0200] "GET /avatars/large/poko.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
::1 - - [18/Oct/2024:13:32:32 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
102.110.238.64 - - [18/Oct/2024:13:32:33 +0200] "GET /avatars/small/g_w.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:33 +0200] "GET /avatars/large/g_w.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
::1 - - [18/Oct/2024:13:32:33 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
102.110.238.64 - - [18/Oct/2024:13:32:33 +0200] "GET /avatars/large/saw.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:33 +0200] "GET /avatars/small/saw.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
::1 - - [18/Oct/2024:13:32:34 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:35 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
102.110.238.64 - - [18/Oct/2024:13:32:35 +0200] "GET /avatars/small/bosco.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.110.238.64 - - [18/Oct/2024:13:32:35 +0200] "GET /avatars/large/bosco.png HTTP/1.1" 404 515 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
::1 - - [18/Oct/2024:13:32:36 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:37 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:38 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:39 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:41 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:13:32:42 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
:

**Comment by ItsOnlyBinary** [comment]
The 404's are to be expected for users that did not yet upload an avatar.

Is upload working, they should be going to the directory you set within the php file

**Comment by rezolixx** [comment]
It does not do any downloading.

102.110.238.64 - - [18/Oct/2024:14:35:00 +0200] "OPTIONS /api.php HTTP/1.1" 403 2784 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"

**Comment by ItsOnlyBinary** [comment]
403 is forbidden, maybe you need to add +x to the api.php

**Comment by rezolixx** [comment]
I did everything and same problem
this log for access.log

102.110.238.64 - - [18/Oct/2024:18:23:34 +0200] "GET /static/fonts/Roboto-Black.ba109b00.woff2 HTTP/1.1" 200 66665 "https://tchat.tchat.chat/static/css/app.5b62c642.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/saw.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/technicien.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/rocking.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/bosco.png HTTP/1.1" 404 841 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/saw.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/g_w.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/small/mad.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/technicien.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/rocking.png HTTP/1.1" 404 841 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/bosco.png HTTP/1.1" 404 841 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/g_w.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:35 +0200] "GET /var/www/html/avatars/large/mad.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/large/saw.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/small/saw.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/small/g_w.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/small/mad.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/large/g_w.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:36 +0200] "GET /var/www/html/avatars/large/mad.png HTTP/1.1" 404 517 "https://tchat.tchat.chat/?nick=saw&age=22&sexe=M&ville=Tunisie&chatnow=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
102.110.238.64 - - [18/Oct/2024:18:23:43 +0200] "OPTIONS /api.php HTTP/1.1" 403 2783 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
::1 - - [18/Oct/2024:18:23:43 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"
::1 - - [18/Oct/2024:18:23:50 +0200] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f (internal dummy connection)"

**Comment by ItsOnlyBinary** [comment]
102.110.238.64 - - [18/Oct/2024:18:23:43 +0200] "OPTIONS /api.php HTTP/1.1" 403 2783 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"

^^^ this looks like a avatar upload attempt and the 403 forbidden is likely a permissions issue or problem with you httpd + php setup

**Comment by rezolixx** [comment]
[Fri Oct 18 20:30:47.146191 2024] [php:warn] [pid 595875] [client 162.158.149.146:41044] PHP Warning:  Undefined array key "HTTP_AUTHORIZATION" in /var/www/html/server-php/api.php on line 54, referer: https://tchat.tchat.chat/
[Fri Oct 18 20:30:47.146227 2024] [php:notice] [pid 595875] [client 162.158.149.146:41044] Token not provided., referer: https://tchat.tchat.chat/

**Comment by ItsOnlyBinary** [comment]
ok that looks closer, i suspect you need to add `CGIPassAuth On` to your apache virtual server config or a `.htaccess` file

https://stackoverflow.com/a/69021772

**Comment by rezolixx** [comment]
Hello @ItsOnlyBinary  thankyou for replay 

102.107.21.27 - - [19/Oct/2024:19:30:54 +0200] "OPTIONS /avatars/api.php HTTP/1.1" 200 707 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.107.21.27 - - [19/Oct/2024:19:30:54 +0200] "POST /avatars/api.php HTTP/1.1" 401 769 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"

**Comment by ItsOnlyBinary** [comment]
check apache error log for why the 401 on POST

**Comment by rezolixx** [comment]
Could you please give me your email so I can give you the server data to check it. Thank you.


Sat Oct 19 20:18:22.548078 2024] [php:warn] [pid 619801] [client 102.107.21.27:6324] PHP Warning:  Undefined array key "HTTP_AUTHORIZATION" in /var/www/html/kiwi/static/avatars/api.php on line 53, referer: https://tchat.tchat.chat/
[Sat Oct 19 20:18:22.548133 2024] [php:notice] [pid 619801] [client 102.107.21.27:6324] Token not provided., referer: https://tchat.tchat.chat/
[Sat Oct 19 20:18:28.051474 2024] [php:warn] [pid 619801] [client 102.107.21.27:6324] PHP Warning:  Undefined array key "HTTP_AUTHORIZATION" in /var/www/html/kiwi/static/avatars/api.php on line 53, referer: https://tchat.tchat.chat/
[Sat Oct 19 20:18:28.051501 2024] [php:notice] [pid 619801] [client 102.107.21.27:6324] Token not provided., referer: https://tchat.tchat.chat/
[Sat Oct 19 20:18:53.313580 2024] [php:warn] [pid 619803] [client 102.107.21.27:6099] PHP Warning:  Undefined array key "HTTP_AUTHORIZATION" in /var/www/html/kiwi/static/avatars/api.php on line 53, referer: https://tchat.tchat.chat/
[Sat Oct 19 20:18:53.313626 2024] [php:notice] [pid 619803] [client 102.107.21.27:6099] Token not provided., referer: https://tchat.tchat.chat/

**Comment by ItsOnlyBinary** [comment]
did you do the `CGIPassAuth On` thing? seems it still not giving the token to php

**Comment by rezolixx** [comment]
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName app.tchat.chat
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/kiwi/static/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
<Directory /var/www/html/kiwi/static/avatars/>
    AllowOverride All
</Directory>

<Directory /var/www/html/kiwi/static/avatars/>
        CGIPassAuth On
    </Directory>

Include /etc/letsencrypt/options-ssl-apache.conf
ServerAlias app.tchat.chat
SSLCertificateFile /etc/letsencrypt/live/app.tchat.chat/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/app.tchat.chat/privkey.pem
</VirtualHost>
</IfModule>
<IfModule mod_ssl.c>

```

**Comment by ItsOnlyBinary** [comment]
and reloaded apache so it got the new config?

**Comment by rezolixx** [comment]
yes i make reload and restart same problem my email benahmed.aymen85@gmail.com please add me chat goolge

102.107.21.27 - - [19/Oct/2024:22:12:20 +0200] "OPTIONS /avatars/api.php HTTP/1.1" 200 2935 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"
102.107.21.27 - - [19/Oct/2024:22:12:21 +0200] "POST /avatars/api.php HTTP/1.1" 401 2976 "https://tchat.tchat.chat/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0"

[Sat Oct 19 22:12:21.623982 2024] [php:notice] [pid 621137] [client 102.107.21.27:6133] Error: Failed to decode token: Signature verification failed, referer: https://tchat.tchat.chat/

**Comment by ItsOnlyBinary** [comment]
`Signature verification failed` <-- that error sounds like `JWT_KEY` does not match what you have in your ircd/webircgateway to generate extjwt token.


sorry i dont have google chat, irc.libera.chat #kiwiirc

**Comment by rezolixx** [comment]
Thanks bro im in server libera.chat
